// Chef Troupe data extracted from CT.xlsx
// Each entry contains District code, Groupe name, Troupe name, CT name, and Email

export const ctData = [
  { district: "BEK", groupe: "Christ Roi, Zahlé", troupe: "Troupe Chevaux", name: "Peter Istanbouly", email: "istanboulyp@gmail.com" },
  { district: "BEK", groupe: "Notre Dame du Secours, Maalka", troupe: "Troupe Eclaireurs", name: "Charbel Jabbour", email: "charbeljabour2020@gmail.com" },
  { district: "BEK", groupe: "Saint Antoine, Jdeidet El Fekha", troupe: "Troupe Eclaireurs", name: "Elias El Khoury", email: "elkhourylias@gmail.com" },
  { district: "BEY1", groupe: "Antranik Sevan, Sin El Fil", troupe: "Troupe Eclaireurs", name: "Garo Sahakian", email: "sahakiangarocris@gmail.com" },
  { district: "BEY1", groupe: "Baden Powell, N.D. de Nazareth, Achrafieh", troupe: "Troupe Eclaireurs", name: "Alex Fakhoury", email: "alex.fakhouryxx@gmail.com" },
  { district: "BEY1", groupe: "Sacré-Coeur, Gemmayzé", troupe: "Troupe Etoile", name: "Khoury Hanna Maroun", email: "marounkhouryhanna242004@gmail.com" },
  { district: "BEY1", groupe: "Sacré-Coeur, Gemmayzé", troupe: "Troupe Flamme", name: "Lionel Hajj", email: "lionelhajj@gmail.com" },
  { district: "BEY1", groupe: "Sagesse, Achrafieh", troupe: "Troupe Saint Augustin", name: "Elias El Jaji", email: "eljajielias@gmail.com" },
  { district: "BEY1", groupe: "Sagesse, Achrafieh", troupe: "Troupe Saint Ignace", name: "Joe Assaad", email: "joeassaad6@gmail.com" },
  { district: "BEY1", groupe: "Saint Antoine De Padoue, Horch Tabet", troupe: "Troupe Maori", name: "Elie Naddaf", email: "elienaddaf10@gmail.com" },
  { district: "BEY1", groupe: "Saint Vincent de Paul, Achrafieh", troupe: "Troupe Phoenix", name: "Kevin Nahra", email: "kevinnahra058@gmail.com" },
  { district: "BEY1", groupe: "Sainte Rita Di Cascia, Sin El Fil", troupe: "Troupe Acquiris", name: "Julien Atallah", email: "julatallah123@gmail.com" },
  { district: "BEY2", groupe: "Besançon, Baabda", troupe: "Troupe Astre Lumineux", name: "Alexandre Sabbak", email: "sabbakalexandre@gmail.com" },
  { district: "BEY2", groupe: "Carmel-Elysée, Hazmieh", troupe: "Troupe Tonnerre", name: "Karl Beyrouti", email: "karl@josephbeyrouti.com" },
  { district: "BEY2", groupe: "Franciscaines, Badaro", troupe: "Troupe Eclaireurs", name: "Joseph Assaf", email: "josephassaf2003@gmail.com" },
  { district: "BEY2", groupe: "Frères Notre Dame, Furn El Chebbak", troupe: "Troupe Horizon", name: "Melhem Hashem", email: "melhemahashem@gmail.com" },
  { district: "BEY2", groupe: "Melkart, Louaizeh", troupe: "Troupe Orion", name: "Fredy Suidan", email: "troupeorion.melkart@gmail.com" },
  { district: "BEY2", groupe: "Notre Dame de la Délivrande, Araya", troupe: "Troupe Eclaireurs", name: "Bechara Khairallah", email: "bechara.khairallah5@gmail.com" },
  { district: "BEY2", groupe: "Notre Dame, Jamhour", troupe: "Troupe 2eme", name: "David Boustany", email: "boustanydavid16@gmail.com" },
  { district: "BEY2", groupe: "Notre Dame, Jamhour", troupe: "Troupe 3eme", name: "Wissam Azoury", email: "wissamazoury55@gmail.com" },
  { district: "BEY2", groupe: "Sagesse, St Jean, Brasilia", troupe: "Troupe Flamme", name: "Marc Andraos", email: "marc.andraos05@gmail.com" },
  { district: "BEY2", groupe: "Sagesse, St Jean, Brasilia", troupe: "Troupe Lumière", name: "Karl Andraos", email: "karl.andraos05@gmail.com" },
  { district: "BEY2", groupe: "Sagesse, St Jean, Brasilia", troupe: "Troupe Zénith", name: "Georges El Khoury", email: "georgeskhoury12094@gmail.com" },
  { district: "BEY2", groupe: "Saints Coeurs, Hadath", troupe: "Troupe Prémice", name: "Mohamad Knio", email: "mbaderknio55@gmail.com" },
  { district: "LN1", groupe: "Bayader Rachiine", troupe: "Troupe Eclaireurs", name: "Nazih Abrass", email: "nazihabrass01@gmail.com" },
  { district: "LN1", groupe: "C.J.C., Tripoli", troupe: "Troupe Eclaireurs", name: "Rony Chiha", email: "ronychiha10@gmail.com" },
  { district: "LN1", groupe: "De La Salle, Kfaryachit", troupe: "Troupe Eclaireurs", name: "Jonathan Hosry", email: "jonathanhosry93@gmail.com" },
  { district: "LN1", groupe: "Harf Ardeh", troupe: "Troupe Eclaireurs", name: "Sarkis Fadlallah", email: "sarkisfadlallah0@gmail.com" },
  { district: "LN1", groupe: "Notre Dame du Mont Carmel, Mejdlaya", troupe: "Troupe Eclaireurs", name: "Johnny El Bachawati", email: "johnnybachawati@gmail.com" },
  { district: "LN1", groupe: "Saint Daniel, Hadath El Jebbeh", troupe: "Troupe Eclaireurs", name: "Jude Al Alam", email: "alalamjude@gmail.com" },
  { district: "LN1", groupe: "Saint Esprit, Zgharta Zawyeh", troupe: "Troupe Eclaireurs", name: "Jad Touma", email: "jadtouma4@gmail.com" },
  { district: "LN1", groupe: "Saint Joseph, Dahr el Ain", troupe: "Troupe Aciano", name: "Joseph Madi", email: "josephmadi61@gmail.com" },
  { district: "LN2", groupe: "Saint Joseph, Capucins, Batroun", troupe: "Troupe Apaches", name: "Joseph Nicolas", email: "josephnicolas1905@gmail.com" },
  { district: "LN2", groupe: "Saint Maron, Chekka", troupe: "Troupe Cathiope", name: "Sarkis Sarkis", email: "sarkissarkis2003@gmail.com" },
  { district: "LN2", groupe: "Saints Coeurs, Batroun", troupe: "Troupe Alpha", name: "Jeanclaude Bakhos", email: "jeanclaudebakhos12@gmail.com" },
  { district: "LN3", groupe: "Notre Dame de la Paix, Kobayat", troupe: "Troupe Eclaireurs", name: "Chris Hakme", email: "chrishakme@gmail.com" },
  { district: "LN3", groupe: "Notre Dame du Mont Carmel, Kobayat", troupe: "Troupe Eclaireurs", name: "Gerard Chidiac", email: "gerardchidiac142@gmail.com" },
  { district: "LN3", groupe: "Saint Joseph, Andaket", troupe: "Troupe Eclaireurs", name: "Ghady Zakhour", email: "gzakhour2004@hotmail.com" },
  { district: "LN3", groupe: "Sainte Moura, Kobayat", troupe: "Troupe Eclaireurs", name: "Joseph Houssein", email: "josephhsein42@gmail.com" },
  { district: "LS1", groupe: "Notre Dame, Maghdouché", troupe: "Troupe Eclaireurs", name: "Wafic Khalil", email: "wafickhalil20062020@gmail.com" },
  { district: "LS1", groupe: "Saint Georges, Debel", troupe: "Troupe Eclaireurs", name: "Fadi Attieh", email: "attiehfadi72@gmail.com" },
  { district: "LS1", groupe: "Saint Georges, Mieh w Mieh", troupe: "Troupe Eclaireurs", name: "Elie Saikaly", email: "saikalyelie11@gmail.com" },
  { district: "LS1", groupe: "Saint Georges, Rmeich", troupe: "Troupe Chevaliers", name: "Andrew Andrawos", email: "andrewandt20@gmail.com" },
  { district: "LS1", groupe: "Saints Coeurs, Jezzine", troupe: "Troupe 816", name: "Fady Harfouch", email: "fadyharfouche0@gmail.com" },
  { district: "ML1", groupe: "Mar Doumit, Sin El Fil", troupe: "Troupe Tonnerre", name: "Charbel Braikaa", email: "braikaacharbel@gmail.com" },
  { district: "ML1", groupe: "Notre Dame des Apotres, Sabtieh", troupe: "Troupe Argo Navis", name: "Andrew Semaan", email: "andrew.semaan@lau.edu" },
  { district: "ML1", groupe: "Notre Dame, Fanar", troupe: "Troupe Cavaliers", name: "Joe Saad", email: "joesaad333@gmail.com" },
  { district: "ML1", groupe: "Saint Maron, Bauchrieh", troupe: "Troupe Eclaireurs", name: "Marcos Bousaid", email: "markisiobousaid@gmail.com" },
  { district: "ML1", groupe: "Saint Mesrob, Borj Hammoud", troupe: "Troupe Eclaireurs", name: "Shant Soulian", email: "shant.soulian@gmail.com" },
  { district: "ML1", groupe: "Saint Vincent de Paul, Borj Hammoud", troupe: "Troupe Eclaireurs", name: "Pio Habib", email: "piohabibuni@gmail.com" },
  { district: "ML1", groupe: "Sainte Rita, Sin El Fil", troupe: "Troupe Eclaireurs", name: "Angelo Fares", email: "angfa2005@gmail.com" },
  { district: "ML2", groupe: "Frères, Baskinta", troupe: "Troupe Eclaireurs", name: "Cesar-Anthony El Alam", email: "cesaralam5@gmail.com" },
  { district: "ML2", groupe: "Jesus and Mary, Kornet Chehwan", troupe: "Troupe Sainte Claudine", name: "Nijad Chaaya", email: "nijadchaaya@gmail.com" },
  { district: "ML2", groupe: "Notre Dame de la Delivrance, Bikfaya", troupe: "Troupe Eclaireurs", name: "Jeffry Hoayek", email: "hoayekjeffry04@gmail.com" },
  { district: "ML2", groupe: "Notre Dame de la Délivrance, Breij", troupe: "Troupe Eclaireurs", name: "Ralph Bou Kheir", email: "ralfbk24@gmail.com" },
  { district: "ML2", groupe: "Notre Dame du Rosaire, Kornet El Hamra", troupe: "Troupe Hercules", name: "Michel Fadel", email: "michelfadel2004@gmail.com" },
  { district: "ML2", groupe: "Saint Antoine, Beit Chabeb", troupe: "Troupe Eclaireurs", name: "Joey Azar", email: "joeyazar05@gmail.com" },
  { district: "ML2", groupe: "Saint Joseph, Kornet Chehwan", troupe: "Troupe Cabestan", name: "Cyril Bou Karam", email: "cyrilbk6@gmail.com" },
  { district: "ML2", groupe: "Saint Joseph, Kornet Chehwan", troupe: "Troupe Carré", name: "Nicolas Nakhle", email: "nakhlenicolas8899@gmail.com" },
  { district: "ML2", groupe: "Saint Joseph, Kornet Chehwan", troupe: "Troupe Carrik", name: "Naamtallah Bou Zerdan", email: "naamtallahbouzerdan@gmail.com" },
  { district: "ML2", groupe: "Saint Maron, Mazraat Yachouh", troupe: "Troupe Sphynx", name: "Nicolas Bayda", email: "nicolaosb30@gmail.com" },
  { district: "ML3", groupe: "Animation Sportive, Zouk Mikael", troupe: "Troupe Phoenix", name: "Joe Razzouk", email: "joerazzouk.1221@gmail.com" },
  { district: "ML3", groupe: "Apôtres, Jounieh", troupe: "1ère Troupe", name: "Johnny Maanak", email: "maanakjohnny@gmail.com" },
  { district: "ML3", groupe: "Apôtres, Jounieh", troupe: "2ème Troupe", name: "Ghadi Habib", email: "habibghadi2005@hotmail.com" },
  { district: "ML3", groupe: "Apôtres, Jounieh", troupe: "3ème Troupe", name: "Badran Chris", email: "chrisbadran01@gmail.com" },
  { district: "ML3", groupe: "G.S.S., Jounieh", troupe: "Troupe Boréale", name: "Saliba Joseph", email: "josephmsaliba77@gmail.com" },
  { district: "ML3", groupe: "G.S.S., Jounieh", troupe: "Troupe Pégase", name: "Stephan Antoun", email: "antounstephan@gmail.com" },
  { district: "ML3", groupe: "Sahel Alma", troupe: "Troupe Phoenix", name: "Jad Achkar", email: "jadjachkar1@gmail.com" },
  { district: "ML3", groupe: "Saint Francois d'Assise, Paradis d'enfants, Jounieh", troupe: "Troupe Eclaireurs", name: "Youssef Abi Nakhoul", email: "joeabinakhoul52@gmail.com" },
  { district: "ML3", groupe: "Saint Joseph, Antoura", troupe: "Troupe A", name: "Elie Hajj", email: "hajj.elie2005@gmail.com" },
  { district: "ML3", groupe: "Saint Joseph, Antoura", troupe: "Troupe B", name: "Karim Khalil", email: "karimissamkhalil2@gmail.com" },
  { district: "ML3", groupe: "Sainte Famille Française, Jounieh", troupe: "Troupe Eclaireurs", name: "Matheo Bou Chaaya", email: "matheobouchaaya@gmail.com" },
  { district: "ML4", groupe: "Saint Georges, Majed El Meouch", troupe: "Troupe Eclaireurs", name: "Maroun El Tekly", email: "marouneltekly@gmail.com" },
  { district: "ML4", groupe: "Saint Michel, Damour", troupe: "Troupe Eclaireurs", name: "Miguel Matar", email: "miguelmatar7548@gmail.com" },
  { district: "ML4", groupe: "Saydet El Talleh, Deir El Kamar", troupe: "Troupe Eclaireurs", name: "Yorgo Azzi", email: "yorgoazzi8@gmail.com" },
  { district: "ML5", groupe: "Mont La Salle, Ain Saadé", troupe: "Troupe Chevaliers", name: "Roy Salamoun", email: "salamounroy@gmail.com" },
  { district: "ML5", groupe: "Mont La Salle, Ain Saadé", troupe: "Troupe Mousquetaires", name: "Ralph Dagher", email: "ralphmdagher77@gmail.com" },
  { district: "ML5", groupe: "Mont La Salle, Ain Saadé", troupe: "Troupe Peaux-Rouges", name: "Theo Haddad", email: "theoelhaddad@gmail.com" },
  { district: "ML5", groupe: "Sagesse High School, Ain Saadé", troupe: "Troupe Aztecs", name: "Toufic Bou Chaaya", email: "toufic.bou.chaaya@icloud.com" },
  { district: "ML5", groupe: "Saint Antoine, Baabdat", troupe: "Troupe Eclaireurs", name: "Anthony Bou Jaoude", email: "boujaoudeanthony@icloud.com" },
  { district: "ML5", groupe: "Sainte Famille, Fanar", troupe: "Troupe Centaure", name: "Yaman Rawad", email: "rawadyaman7@gmail.com" },
  { district: "ML5", groupe: "Sainte Famille, Fanar", troupe: "Troupe Griffons", name: "Jad Aoun", email: "aounjad03@gmail.com" },
  { district: "ML5", groupe: "Sainte Marie, Beit Mery", troupe: "Troupe Eclaireurs", name: "Jean Paul Abi Abboud", email: "abiabboudjeanpaul@gmail.com" },
  { district: "ML5", groupe: "Sainte Marina, Daychounieh", troupe: "Troupe Eclaireurs", name: "Charbel Sakr", email: "charbelsk2019@gmail.com" },
  { district: "ML5", groupe: "Sainte Rafqa, Tilal Ain Saadé", troupe: "Troupe Eclaireurs", name: "Jeffry Aoun", email: "jefryaoun8@gmail.com" },
  { district: "ML5", groupe: "Saints Coeurs, Ain Najm", troupe: "Troupe Cavaliers", name: "Johnny El Ramy", email: "elramy.johnny@gmail.com" },
  { district: "ML5", groupe: "Saints Coeurs, Ain Najm", troupe: "Troupe Ouragan", name: "Robin Matar", email: "robin-matar@hotmail.com" },
  { district: "ML6", groupe: "Daroun, Daroun-Harissa", troupe: "Troupe Notre Dame", name: "Charbel Chidiac", email: "charbelchidiac1001@gmail.com" },
  { district: "ML6", groupe: "Ecole Allemande, Jounieh", troupe: "Troupe Eclaireurs", name: "Andreas Khalil", email: "andreaskhalil23@gmail.com" },
  { district: "ML6", groupe: "Notre Dame Habchieh, Ghazir", troupe: "Troupe Eclaireurs", name: "Joe Obeid", email: "joeobeid1995@gmail.com" },
  { district: "ML6", groupe: "Saint Jacques, Bouar", troupe: "Troupe Eclaireurs", name: "Maroun Farah", email: "mlg.maroun@gmail.com" },
  { district: "ML6", groupe: "Saint Sacrement, Beit Habbak", troupe: "Troupe Eclaireurs", name: "Marc Boumalhab", email: "marcboumalhab46@gmail.com" },
  { district: "ML6", groupe: "Saints Coeurs, Jbeil", troupe: "Troupe Eclaireurs", name: "Christophe Al Boustany", email: "chris.boustany2005@gmail.com" },
  { district: "ML6", groupe: "Saints Coeurs, Kfarhbab", troupe: "Troupe 1", name: "Carl Merhi", email: "carl.merhi@outlook.com" },
  { district: "ML6", groupe: "Saints Coeurs, Kfarhbab", troupe: "Troupe 2", name: "Jad Abdel Jalil", email: "jadabdeljalil1999@gmail.com" },
  { district: "ML7", groupe: "Antranik, Antelias", troupe: "Troupe Eclaireurs", name: "Garo Nadjarian", email: "garonadjarian29@gmail.com" },
  { district: "ML7", groupe: "Athénée de Beyrouth, Bsalim", troupe: "Troupe Eclipse", name: "Marco Samarani", email: "marcosamarani1@gmail.com" },
  { district: "ML7", groupe: "Sagesse Saint Marons, Jdeideh", troupe: "Troupe Cyclone", name: "Cesar Ayoub", email: "cesar.ayoub20102004@gmail.com" },
  { district: "ML7", groupe: "Saint Esprit, Kobeize", troupe: "Troupe Pégase", name: "Marc Bassil", email: "mabassil04@gmail.com" },
  { district: "ML7", groupe: "Saint Esprit, Kobeize", troupe: "Troupe Phénix", name: "Hrant Elmayan", email: "hrantelmayan@gmail.com" },
  { district: "ML7", groupe: "Saint Georges, Zalka", troupe: "Troupe Magma", name: "Peter Freiha", email: "peter.freiha@outlook.com" },
  { district: "ML7", groupe: "Saint Vincent de Paul, Naccache", troupe: "Troupe Eclaireurs", name: "Johnny Lahoud", email: "johnnylahoud77@gmail.com" },
  { district: "ML7", groupe: "Saints Coeurs, Bauchrieh", troupe: "Troupe Batelier", name: "Dib Khoury", email: "deebkhoury284@gmail.com" },
  { district: "ML7", groupe: "Val Père Jacques, Bkenaya", troupe: "Troupe Impeesa", name: "Charbel Rassy", email: "rassycharbel14@gmail.com" },
  { district: "ML7", groupe: "Val Père Jacques, Bkenaya", troupe: "Troupe Koudou", name: "Jonathan Dahdah", email: "jonathandahdah5@gmail.com" },
  { district: "ML8", groupe: "Champville, Dik El Mehdi", troupe: "Troupe Apaches", name: "Jeffry Diab", email: "jeffryjdiab@gmail.com" },
  { district: "ML8", groupe: "Champville, Dik El Mehdi", troupe: "Troupe Bannocks", name: "Maurice Challita", email: "mauricechallita9@gmail.com" },
  { district: "ML8", groupe: "Champville, Dik El Mehdi", troupe: "Troupe Cherokees", name: "Tony Abourjeily", email: "23tonyar@gmail.com" },
  { district: "ML8", groupe: "Champville, Dik El Mehdi", troupe: "Troupe Comanches", name: "Peter Raffoul", email: "peterraffoul0@gmail.com" },
  { district: "ML8", groupe: "Mar Ephrem, Kfardebian", troupe: "Troupe Eclaireurs", name: "Jerome Tayeh", email: "jeromejuniortayeh@gmail.com" },
  { district: "ML8", groupe: "Notre Dame de Louaizé, Zouk Mosbeh", troupe: "Troupe Eclair", name: "Jimmy Sfeir", email: "jimmysfeir22@gmail.com" },
  { district: "ML8", groupe: "Notre Dame de Louaizé, Zouk Mosbeh", troupe: "Troupe Soleil", name: "Jean-Paul Elias", email: "jayp.g.elias@gmail.com" },
  { district: "ML8", groupe: "Notre Dame, Zakrit", troupe: "Troupe Eclaireurs", name: "Youssef Semaan", email: "ysemaan979@gmail.com" },
  { district: "ML8", groupe: "Saint Michel, Jeita", troupe: "Troupe Eclaireurs", name: "Peter Saad", email: "peter.s.saad.2006@gmail.com" },
  { district: "ML8", groupe: "Saint Vincent de Paul, Ajaltoun", troupe: "Troupe Saint Vincent de Paul", name: "Zahi Al Haddad", email: "zahihadad76@gmail.com" },
];
